# ci.yml
name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        working-directory: ./TodoListClient
        run: dotnet restore TodoListClient.csproj
        
      - name: Set Build Number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build
        working-directory: ./TodoListClient
        run: dotnet build TodoListClient.csproj --configuration Release --no-restore -p:Version=1.0.${{ env.BUILD_NUMBER }}

      - name: Publish
        working-directory: ./TodoListClient     
        run: dotnet publish TodoListClient.csproj --configuration Release --no-build --output ./publish

      - uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ env.BUILD_NUMBER }}
          path: publish/**
